import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Loader from "@/components/ui/initial-loader";
import Navbar from "@/components/ui/navbar";



const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`p-6 ${dmSans.className} bg-[#FAF9F6]`}>
        <Loader />
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
